service: rekognition-analysis-s3-image

frameworkVersion: ">=1.10.0"

custom:
  bucket: dark-cloud-bucket

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 10
  stage: dev
  region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::dark-cloud-bucket or *"

package:
 include:
   - categorize/**

functions:
  imageAnalysis:
    handler: categorize.categorize_and_move_image
    events:
      - existings3:
          bucket: dark-cloud-bucket
          events: 
            - s3:ObjectCreated:*
          rules:
            - prefix: archive/
plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3
